services:
  # Backend service
  - type: web
    name: hotel-recommender-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: https://hotel-recommender-frontend.onrender.com

  # Frontend service
  - type: web
    name: hotel-recommender-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm start
    envVars:
      - key: REACT_APP_API_URL
        value: https://hotel-recommender-backend.onrender.com 