services:
  # Backend service
  - type: web
    name: hotel-finder-backend
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://mis:mis123@cluster0.c2up9.mongodb.net/h1
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: https://front-end-atrw.onrender.com
      - key: CORS_ORIGIN
        value: https://front-end-atrw.onrender.com
    rootDir: .
    autoDeploy: true

  # Frontend service
  - type: static
    name: hotel-finder-frontend
    env: static
    buildCommand: |
      echo "Starting build process..."
      echo "Current directory: $(pwd)"
      echo "Listing directory contents:"
      ls -la
      echo "Changing to client directory..."
      cd client
      echo "Installing dependencies..."
      npm install --legacy-peer-deps
      echo "Building React app..."
      npm run build
      echo "Build completed. Listing build directory:"
      ls -la build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend-f428.onrender.com
      - key: NODE_ENV
        value: production
      - key: CI
        value: false
    rootDir: .
    autoDeploy: true 