services:
  # Backend service
  - type: web
    name: hotel-finder-backend
    env: node
    buildCommand: |
      cd client && npm install && npm run build
      cd ../Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://mis:mis123@cluster0.c2up9.mongodb.net/h1
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        sync: false
    rootDir: .
    autoDeploy: true

  # Frontend service
  - type: web
    name: hotel-finder-frontend
    env: node
    buildCommand: |
      npm install -g serve
      cd client && npm install && npm run build
    startCommand: cd client && serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://backend-f428.onrender.com
    rootDir: .
    autoDeploy: true 